#!/bin/bash
# ============================================================
# TabFact 完整研究流程 - 快速命令参考
# ============================================================
# 使用方法: 阅读此脚本了解每个步骤的命令

echo "============================================================"
echo "TabFact 完整研究流程 - 快速命令参考"
echo "============================================================"
echo ""
echo "【环境配置】"
echo "conda activate rethinking"
echo "export PATH=\"/data/amax/home/E23101002/.conda/envs/rethinking/bin:\$PATH\""
echo ""
echo "============================================================"
echo "【阶段一】生成推理步骤 (对应研究步骤1-2)"
echo "============================================================"
echo ""
echo "--- DeepSeek 跑训练集 (0-4000) ---"
echo "bash scripts/run_deepseek_tabtrain.sh 0 4000"
echo "# 输出: output/deepseek_tabtrain/result.jsonl"
echo ""
echo "--- Qwen 跑训练集 (0-4000) ---"
echo "bash scripts/run_qwen_tabtrain.sh 0 4000"
echo "# 输出: output/qwen_tabtrain/result.jsonl"
echo ""
echo "--- Llama 跑训练集 (0-4000) ---"
echo "bash scripts/run_llama_tabtrain.sh 0 4000"
echo "# 输出: output/llama_tabtrain/result.jsonl"
echo ""
echo "============================================================"
echo "【阶段二】分类正确/错误样本 (对应研究步骤3)"
echo "============================================================"
echo ""
echo "python scripts/split_correct_incorrect.py output/deepseek_tabtrain/result.jsonl"
echo "python scripts/split_correct_incorrect.py output/qwen_tabtrain/result.jsonl"
echo "python scripts/split_correct_incorrect.py output/llama_tabtrain/result.jsonl"
echo "# 输出: correct.jsonl 和 incorrect.jsonl"
echo ""
echo "============================================================"
echo "【阶段三】构建训练数据集"
echo "============================================================"
echo ""
echo "--- 使用Qwen ---"
echo "bash scripts/build_training_quick.sh"
echo ""
echo "--- 使用Llama ---"
echo "bash scripts/build_training_quick.sh llama"
echo "# 输出: training_data/positive_samples.jsonl, training_data/negative_samples.jsonl"
echo ""
echo "============================================================"
echo "【阶段四】DeepSeek分析推理步骤 (对应研究步骤4)"
echo "============================================================"
echo ""
echo "cd buzhou/training_data_zhengti"
echo "bash run_analysis.sh 0 2000    # 处理0-1999"
echo "bash run_analysis.sh 2000 4000 # 处理2000-3999"
echo ""
echo "============================================================"
echo "【阶段五】构建微调数据集 (对应研究步骤5)"
echo "============================================================"
echo ""
echo "cd buzhou/training_data_zhengti/weitiao"
echo "python build_finetuning_dataset.py"
echo "# 输出: training_finetuning_dataset.jsonl"
echo ""
echo "============================================================"
echo "【阶段六】LoRA微调 (对应研究步骤6)"
echo "============================================================"
echo ""
echo "cd buzhou/training_data_zhengti/weitiao"
echo "bash train_qwen3_lora_final.sh   # Qwen版本"
echo "# 或者"
echo "bash train_llama_lora.sh         # Llama版本(需要创建)"
echo ""
echo "# 合并LoRA权重"
echo "bash merge_lora.sh"
echo ""
echo "============================================================"
echo "【阶段七】三轮迭代推理验证 (对应研究步骤7-11)"
echo "============================================================"
echo ""
echo "--- Qwen基座 + Qwen分析师 ---"
echo "nohup bash fenxishi/run_voting_tabfact.sh > fenxishi/output/parallel_voting_tabfact/nohup.log 2>&1 &"
echo ""
echo "--- Llama基座 + Llama分析师 ---"
echo "nohup bash fenxishi/run_voting_tabfact_llama.sh > fenxishi/output/parallel_voting_tabfact_llama/nohup.log 2>&1 &"
echo ""
echo "============================================================"
echo "【阶段八】评估结果"
echo "============================================================"
echo ""
echo "python evaluate.py output/deepseek_tabtrain/result.jsonl"
echo "python evaluate.py output/qwen_tabtrain/result.jsonl"
echo "python evaluate.py output/llama_tabtrain/result.jsonl"
echo "python evaluate.py fenxishi/output/parallel_voting_tabfact/result.jsonl"
echo "python evaluate.py fenxishi/output/parallel_voting_tabfact_llama/result.jsonl"
echo ""
echo "============================================================"
echo "【测试集评估】(验证最终效果)"
echo "============================================================"
echo ""
echo "--- DeepSeek 跑测试集 ---"
echo "bash scripts/run_deepseek_tabfact.sh 0 1e6"
echo ""
echo "--- Qwen 跑测试集 ---"
echo "bash buzhou/qwen/all_dp_qwen.sh"
echo ""
echo "--- Llama 跑测试集 ---"
echo "bash scripts/run_llama_tabfact.sh 0 1e6"
echo ""
echo "============================================================"
